changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Minor changes
      labels:
        - minor
    - title: Documentation improvements
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
